paginate: 20
excerpt_separator: "<!--more-->"

name: Простые решения. Заметки зеленого программиста.
url: boonya.info
author: Serhii [boonya] Buynytskyi (me@boonya.info)

gems:
    - jekyll-redirect-from
